.PHONY: clean All

All:
	@echo "----------Building project:[ keypad_simulator - Debug ]----------"
	@cd "keypad" && "$(MAKE)" -f  "keypad_simulator.mk" && "$(MAKE)" -f  "keypad_simulator.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ keypad_simulator - Debug ]----------"
	@cd "keypad" && "$(MAKE)" -f  "keypad_simulator.mk" clean
