.PHONY: clean All

All:
	@echo "----------Building project:[ keypad_hardware - Debug ]----------"
	@cd "keypad_hardware" && "$(MAKE)" -f  "keypad_hardware.mk" && "$(MAKE)" -f  "keypad_hardware.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ keypad_hardware - Debug ]----------"
	@cd "keypad_hardware" && "$(MAKE)" -f  "keypad_hardware.mk" clean
