.PHONY: clean All

All:
	@echo "----------Building project:[ LabThree - Debug ]----------"
	@cd "LabThree" && "$(MAKE)" -f  "LabThree.mk" && "$(MAKE)" -f  "LabThree.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ LabThree - Debug ]----------"
	@cd "LabThree" && "$(MAKE)" -f  "LabThree.mk" clean
