.PHONY: clean All

All:
	@echo "----------Building project:[ 3.1.4 - Debug ]----------"
	@cd "3.1.4" && "$(MAKE)" -f  "3.1.4.mk"
clean:
	@echo "----------Cleaning project:[ 3.1.4 - Debug ]----------"
	@cd "3.1.4" && "$(MAKE)" -f  "3.1.4.mk" clean
